defaults:
  - default.yaml

gpus: -1
accelerator: gpu
#strategy: ddp

replace_sampler_ddp: True
devices: auto
sync_batchnorm: True
auto_scale_batch_size: False

plugins:
  - __target__: pytorch_lightning.plugins.DDPPlugin
    find_unused_parameters: False
