defaults:
  - default.yaml

gpus: -1
accelerator: gpu
strategy: ddp
replace_sampler_ddp: True
sync_batchnorm: True
auto_scale_batch_size: False

plugins:
  - _target_: pytorch_lightning.plugins.DDPPlugin
    find_unused_parameters: False

# milli transformer batch_size=48, gpus=1