_target_: pytorch_lightning.Trainer

gpus: -1

enable_checkpointing: true
strategy: dp
default_root_dir: ${exp_dir}
progress_bar_refresh_rate: 1
enable_progress_bar: True
check_val_every_n_epoch: 1
max_epochs: 250
log_every_n_steps: 1
precision: 32
num_sanity_val_steps: 10
auto_scale_batch_size: False

