job_logging:
  version: 1
  formatters:
    simple:
      level: 'NOTSET'
      format: "%(message)s"
      datefmt: "[%X]"
  handlers:
    rich:
      class: rich.logging.RichHandler
      formatter: simple

  root:
    handlers: [rich]
    level: 'NOTSET'

  disable_existing_loggers: false

hydra_logging:
  version: 1
  formatters:
    simple:
      level: 'INFO'
      format: '[HYDRA] %(message)s'
      datefmt: "[%X]"
  handlers:
    rich:
      class: rich.logging.RichHandler
      formatter: simple
  root:
    level: NOTSET
    handlers:
      - rich
  loggers:
    logging_example:
      level: NOTSET
  disable_existing_loggers: false


