# @package _global_

# default running mode
mode:
  fit: True
  test: True

hydra:
  run:
    dir: ${exp_dir}/hydra-run//${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${exp_dir}/hydra-multirun//${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
