# @package _global_

# default running mode
mode:
  fit: True
  test: True

hydra:
  run:
    dir: ${log_dir}/runs/${name}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${log_dir}/multiruns/${name}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
