# @package _global_

# experiment mode sets name of the logging folder to the experiment name
# can also be used to name the run in the logger
# example usage:
# `python run.py mode=exp name=some_name`

experiment_mode: True

name: ???

hydra:
  run:
    dir: ${log_dir}/runs/${name}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${log_dir}/multiruns/${name}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
