defaults:
  - modus_prime.yaml


image_embedding_config:
    _target_: tali.models.auto_builder.transformers.AutoDumbNet
    embedding_output_features: 512

audio_embedding_config:
    _target_: tali.models.auto_builder.transformers.AutoDumbNet
    embedding_output_features: 512

text_embedding_config:
    _target_: tali.models.auto_builder.transformers.AutoDumbNet
    embedding_output_features: 512

video_embedding_config:
    _target_: tali.models.auto_builder.transformers.AutoDumbNet
    embedding_output_features: 512

name: base_dumbnet