defaults:
  - image_embedding_config: base-image-vi-transformer16.yaml
  - audio_embedding_config: base-audio-convformer.yaml
  - text_embedding_config: base-text-transformer.yaml
  - video_embedding_config: base-video-transformer.yaml
  - optimizer_config: adam.yaml
  - lr_scheduler_config: cosine_annealing.yaml

_target_: tali.models.systems.DumbusPrime

embedding_output_features: 512
logit_scale: 14.2857142857
name: base_dumbnet