defaults:
  - modus_prime.yaml
  - image_embedding_config: milli-image-vi-transformer16.yaml
  - audio_embedding_config: milli-audio-convformer.yaml
  - text_embedding_config: milli-text-transformer.yaml
  - video_embedding_config: milli-video-averager.yaml
  - optimizer_config: adam.yaml
  - lr_scheduler_config: cosine_annealing.yaml

name: milli_modus_prime_vi-transformer16
