defaults:
  - optimizer_config: adam.yaml
  - lr_scheduler_config: cosine_annealing.yaml

_target_: tali.models.systems.ModusPrime

embedding_output_features: 512
num_train_samples: ${datamodule.train_num_samples}
batch_size: ${batch_size}
logit_scale: 1.0