# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: ${wandb_project_name}
  offline: False # set True to store all logs only locally
  resume: ${resume}
  save_dir: ${current_experiment_dir}/
  log_model: 'all'
  id: ${datamodule.config.dataset_name}-${model.name}-${datamodule.config.modality_config.name}-${seed}
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
