# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: 'TALI-gcp-exp'
  name: ${name}
  offline: False # set True to store all logs only locally
  resume: true
  save_dir: ${log_dir}/${name}
  log_model: 'all'
  id: ${name}
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
