# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "TALI-visualizer"
  name: TALI-v-3-2-0
  offline: False # set True to store all logs only locally
  resume: ${resume}
  save_dir: ${current_experiment_dir}/
  log_model: 'all'
  id: ${name}
  prefix: ""
  job_type: "dataset"
  group: ""
  tags: []
