# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: ${wandb-project-name}
  name: ${name}
  offline: False # set True to store all logs only locally
  resume: ${resume}
  save_dir: ${exp_dir}/
  log_model: 'all'
  id: ${name}
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
