defaults:
  - default.yaml

#watch_model:
#  _target_: tali.base.callbacks.wandb_callbacks.WatchModel
#  log: "all"
#  log_freq: 1

upload_code_as_artifact:
  _target_: tali.base.callbacks.wandb_callbacks.UploadCodeAsArtifact
  code_dir: ${code_dir}

upload_ckpts_as_artifact:
  _target_: tali.base.callbacks.wandb_callbacks.UploadCheckpointsAsArtifact
  ckpt_dir: ${current_experiment_dir}/checkpoints/
  upload_best_only: False

log_multi_modal_similarity_prediction_heatmap:
  _target_: tali.base.callbacks.wandb_callbacks.LogMultiModalPredictionHeatmaps
  num_samples: 8

log_grads:
  _target_: tali.base.callbacks.wandb_callbacks.LogGrads
  refresh_rate: 100

log_configs:
  _target_: tali.base.callbacks.wandb_callbacks.LogConfigInformation
  config:
    trainer: ${trainer}
    model: ${model}
    datamodule: ${datamodule}
    logger: ${logger}
    mode: ${mode}
    resume: ${resume}
    checkpoint_path: ${checkpoint_path}
    dataloading_only_run: ${dataloading_only_run}
    visualize_data_locally: ${visualize_data_locally}
    wandb_visualization_config: ${wandb_visualization_config}
    print_config: ${print_config}
    ignore_warnings: ${ignore_warnings}
    logging_level: ${logging_level}
    test_after_training: ${test_after_training}
    batch_size: ${batch_size}
    seed: ${seed}
    name: ${name}
    code_dir: ${code_dir}
    root_experiment_dir: ${root_experiment_dir}
    current_experiment_dir: ${current_experiment_dir}
    train_data_dir: ${train_data_dir}
    val_data_dir: ${val_data_dir}
    test_data_dir: ${test_data_dir}