# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default.yaml
  - model: milli_modus_prime_vi-transformer16.yaml
  - datamodule: base-tali.yaml
  - callbacks: wandb.yaml
  - logger: wandb.yaml # set logger here or use command line (e.g. `python run.py logger=wandb`)

  # modes are special collections of config options for different purposes, e.g. debugging
  - mode: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

ray_multi_run: True
log_dir: /mnt/disk/filestore/experiments

# path to folder with data
data_dir: /mnt/disk/filestore/tali-dataset

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True
logging_level: INFO
# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on metric specified in checkpoint callback
test_after_training: True

batch_size: 2
# seed for random number generators in pytorch, numpy and python.random
seed: 20221601

# name of the run, should be used along with experiment mode
name: ${datamodule.config.dataset_name}-${model.name}-${datamodule.config.modality_config.name}-${seed}


model:
  google_storage_config:
    local_experiments_root_dir: ${log_dir}
    experiment_name: ${name}
    from_scratch: False
    use_google_storage: False
    bucket_name: "tali-experiments"