_target_: tali.datasets.hub.TALIDataModule
config:
  dataset_root: '/mnt/disk/filestore/tali-dataset'
  training_set_size_identifier: base
  dataset_name: ${datamodule.config.training_set_size_identifier}-tali
  modality_config:
    image: true
    audio: true
    video: true
    text: true
    name: video-${datamodule.config.modality_config.video}-audio-${datamodule.config.modality_config.video}-text-${datamodule.config.modality_config.video}-image-${datamodule.config.modality_config.video}
  rescan_paths: false
  num_video_frames_per_datapoint: 10
  num_audio_frames_per_datapoint: 88200
  num_audio_sample_rate: 44100
  image_shape:
    channels: 3
    width: 224
    height: 224
  text_context_length: 77
batch_size: ${batch_size}
persistent_workers: false
pin_memory: true
prefetch_factor: 4
