gcloud compute instances create-with-container instance-1 --project=tali-multi-modal --zone=us-central1-f --machine-type=a2-highgpu-1g --network-interface=network-tier=PREMIUM,subnet=default --maintenance-policy=TERMINATE --service-account=829809103946-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --accelerator=count=1,type=nvidia-tesla-a100\ --image=projects/cos-cloud/global/images/cos-stable-93-16623-39-30\
 --boot-disk-size=10GB\
 --boot-disk-type=pd-balanced\
 --boot-disk-device-name=instance-1\
 --container-image=gcr.io/deeplearning-platform-release/pytorch-gpu.1-10\
 --container-restart-policy=always\
 --container-privileged\
 --no-shielded-secure-boot\
 --shielded-vtpm\
 --shielded-integrity-monitoring\
 --labels=container-vm=cos-stable-93-16623-39-30