_target_: tali.models.auto_builder.transformers.AutoConv1DTransformers
config:
  embedding_output_features: 512
  densenet_num_filters: 8
  densenet_num_stages: 5
  densenet_num_blocks: 1
  grid_patch_size: 64
  densenet_dilated: false
