_target_: tali.models.auto_builder.transformers.AutoConv1DTransformers
config:
  embedding_output_features: 512
  resnet_num_filters: 8
  resnet_num_stages: 5
  resnet_num_blocks: 1
  grid_patch_size: 64
  resnet_dilated: false
