method: grid
metric:
  goal: minimize
  name: validation/overall_cross_entropy/epoch_mean
parameters:
  datamodule_name:
    distribution: categorical
    values:
    - milli
#    - centi
#    - deci
    - base
  model_options:
    distribution: categorical
    values:
    - centi_modus_prime_resnet50
    - base_modus_prime_resnet50
    - centi_modus_prime_vi-transformer16
    - base_modus_prime_vi-transformer16
  use_audio_modality:
    distribution: categorical
    values:
    - "false"
    - "true"
  use_image_modality:
    distribution: categorical
    values:
    - "true"
  use_text_modality:
    distribution: categorical
    values:
    - "true"
    - "false"
  use_video_modality:
    distribution: categorical
    values:
    - "false"
    - "true"
  num_gpus: 8,
  batch_size: 64
program: wandb_sweep/train_eval_search.py